channels:
  - conda-forge

dependencies:
  # Python version and pip
  - python=3.10
  - pip

  - duckdb
  - openpyxl
  - fastexcel
  - ipywidgets
  - jupyter
  - marimo
  - polars
  - pyarrow
  - sqlalchemy
  - sqlglot

  # PIP dependencies
  - pip:
      - quak
